# frozen_string_literal: true

module FlagKit
  module Error
    # Error codes for FlagKit SDK errors.
    module ErrorCode
      # Initialization errors
      INIT_FAILED = "INIT_FAILED"
      INIT_TIMEOUT = "INIT_TIMEOUT"
      INIT_ALREADY_INITIALIZED = "INIT_ALREADY_INITIALIZED"
      INIT_NOT_INITIALIZED = "INIT_NOT_INITIALIZED"

      # Authentication errors
      AUTH_INVALID_KEY = "AUTH_INVALID_KEY"
      AUTH_EXPIRED_KEY = "AUTH_EXPIRED_KEY"
      AUTH_MISSING_KEY = "AUTH_MISSING_KEY"
      AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
      AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"

      # Network errors
      NETWORK_ERROR = "NETWORK_ERROR"
      NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
      NETWORK_RETRY_LIMIT = "NETWORK_RETRY_LIMIT"

      # Evaluation errors
      EVAL_FLAG_NOT_FOUND = "EVAL_FLAG_NOT_FOUND"
      EVAL_TYPE_MISMATCH = "EVAL_TYPE_MISMATCH"
      EVAL_INVALID_KEY = "EVAL_INVALID_KEY"
      EVAL_INVALID_VALUE = "EVAL_INVALID_VALUE"
      EVAL_DISABLED = "EVAL_DISABLED"
      EVAL_ERROR = "EVAL_ERROR"
      EVAL_CONTEXT_ERROR = "EVAL_CONTEXT_ERROR"
      EVAL_DEFAULT_USED = "EVAL_DEFAULT_USED"
      EVAL_STALE_VALUE = "EVAL_STALE_VALUE"
      EVAL_CACHE_MISS = "EVAL_CACHE_MISS"
      EVAL_NETWORK_ERROR = "EVAL_NETWORK_ERROR"
      EVAL_PARSE_ERROR = "EVAL_PARSE_ERROR"
      EVAL_TIMEOUT_ERROR = "EVAL_TIMEOUT_ERROR"

      # Cache errors
      CACHE_READ_ERROR = "CACHE_READ_ERROR"
      CACHE_WRITE_ERROR = "CACHE_WRITE_ERROR"
      CACHE_INVALID_DATA = "CACHE_INVALID_DATA"
      CACHE_EXPIRED = "CACHE_EXPIRED"
      CACHE_STORAGE_ERROR = "CACHE_STORAGE_ERROR"

      # Event errors
      EVENT_QUEUE_FULL = "EVENT_QUEUE_FULL"
      EVENT_INVALID_TYPE = "EVENT_INVALID_TYPE"
      EVENT_INVALID_DATA = "EVENT_INVALID_DATA"
      EVENT_SEND_FAILED = "EVENT_SEND_FAILED"
      EVENT_FLUSH_FAILED = "EVENT_FLUSH_FAILED"
      EVENT_FLUSH_TIMEOUT = "EVENT_FLUSH_TIMEOUT"

      # Circuit breaker errors
      CIRCUIT_OPEN = "CIRCUIT_OPEN"

      # Configuration errors
      CONFIG_INVALID_URL = "CONFIG_INVALID_URL"
      CONFIG_INVALID_INTERVAL = "CONFIG_INVALID_INTERVAL"
      CONFIG_MISSING_REQUIRED = "CONFIG_MISSING_REQUIRED"
      CONFIG_INVALID_API_KEY = "CONFIG_INVALID_API_KEY"
      CONFIG_INVALID_BASE_URL = "CONFIG_INVALID_BASE_URL"
      CONFIG_INVALID_POLLING_INTERVAL = "CONFIG_INVALID_POLLING_INTERVAL"
      CONFIG_INVALID_CACHE_TTL = "CONFIG_INVALID_CACHE_TTL"

      # Security errors
      SECURITY_LOCAL_PORT_IN_PRODUCTION = "SECURITY_LOCAL_PORT_IN_PRODUCTION"
      SECURITY_PII_DETECTED = "SECURITY_PII_DETECTED"
      SECURITY_ENCRYPTION_ERROR = "SECURITY_ENCRYPTION_ERROR"

      RECOVERABLE_CODES = [
        NETWORK_ERROR, NETWORK_TIMEOUT, NETWORK_RETRY_LIMIT,
        CIRCUIT_OPEN, CACHE_EXPIRED, EVAL_STALE_VALUE,
        EVAL_CACHE_MISS, EVAL_NETWORK_ERROR, EVENT_SEND_FAILED
      ].freeze

      def self.recoverable?(code)
        RECOVERABLE_CODES.include?(code)
      end
    end
  end

  # Alias for backward compatibility
  ErrorCode = Error::ErrorCode
end
